name: SonarCloud
on:
  push:
    branches:
      - master
  pull_request:
      - master
jobs:
  sonarcloud:
  name: SonarCloud
  runs-on: ubuntu-latest
  steps:
    -name: Cloning repository
    uses: actions/checkout@v3
    with:
      fetch-depth: 0
    -name: Using Node.js 19.x
      uses: actions/setup-node@v3
      with:
        node-version: 19.x
    -name: Installing dependencies
      run: npm i
    -name: Generating coverage report
      run: npm run coverage
    -name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}